# Generated by Django 5.1.6 on 2025-03-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_cita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
