# Generated by Django 5.1.6 on 2025-04-05 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_mensaje_leido_alter_mensaje_destinatario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonio',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name': 'Testimonio', 'verbose_name_plural': 'Testimonios'},
        ),
        migrations.AddField(
            model_name='testimonio',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Destacar en la página principal'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Aprobado por el administrador'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='comentario',
            field=models.TextField(verbose_name='Comentario del usuario'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='experiencia',
            field=models.CharField(choices=[('excelente', 'Excelente'), ('buena', 'Buena'), ('regular', 'Regular'), ('mala', 'Mala')], default='buena', max_length=10, verbose_name='Nivel de experiencia'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='testimonio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonios', to=settings.AUTH_USER_MODEL),
        ),
    ]
