# Generated by Django 5.1.6 on 2025-04-06 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_testimonio_options_testimonio_destacado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialista',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.especialidad', verbose_name='Especialidad'),
        ),
    ]
