# Generated by Django 5.1.6 on 2025-04-06 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_especialista_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialista',
            name='email',
        ),
        migrations.AddField(
            model_name='especialista',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.especialidad'),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='especialista', to=settings.AUTH_USER_MODEL),
        ),
    ]
